### ISSUE TITLE
Drop Pug, serve static HTML file.

### ISSUE THREAD

**Issue by simnalamburt** [noraesae/pen#10]
[Pug] is not that fast, and has tons of dependencies. While we almost do not use Pug, it seems to be easy to replace it with statically built HTML file.

> As I suggested in #7, using pure HTML5 is possible with inlining CSS and JS in result HTML. Then we do not need to worry about relpath problem and the result will be much simpler(we do not need build.js and build.css). It must be possible with webpack, mustn't it?

I'm planning to use [`html-webpack-inline-source-plugin`]. It'll bring a big change to this project, so I'll do some basic code organization before I start the change.

#### Previous discussions
- https://github.com/noraesae/pen/issues/7
- https://github.com/noraesae/pen/issues/6#issuecomment-270959433

#### TODOs
- [x] Add [`webpack-fail-plugin`](https://github.com/TiddoLangerak/webpack-fail-plugin)
- [x] Misc code cleanup
- [x] Add `--require babel-register` to the mocha
- [x] Use ES2015 import/export syntax to both frontend codes and test codes
- [x] Remove `'use strict';` from module codes
- [x] Replace `React.createClass` with `React.Component`
- [x] Validate props
- [x] Remove the usage of `React.createFactory`
- [x] Lint react codes with [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react)
- [x] Introduce [`html-webpack-plugin`] and [`html-webpack-inline-source-plugin`]
- [x] Drop [Pug]
- [x] Static file serving

[Pug]: https://github.com/pugjs/pug
[`React.PureComponent`]: https://facebook.github.io/react/docs/react-api.html#react.purecomponent
[`html-webpack-plugin`]: https://github.com/ampedandwired/html-webpack-plugin
[`html-webpack-inline-source-plugin`]: https://github.com/DustinJackson/html-webpack-inline-source-plugin

~~WIP in [simnalamburt/pen](https://github.com/simnalamburt/pen)~~ &rarr; Stopped.

**Comment by simnalamburt** [comment]
It's somewhat hard to use brand new feature of ECMAScript in current structure since current test codes does not run under babel. It's because Mocha was invented before the babel and JSX era.

Have you ever tried Facebook [Jest]? Looks like it's much more babel-friendly. It also have built-in coverage reporter unlike mocha. (Yes it is possible to check coverage with mocha but it's [not that comfortable]).

Do do not have tried [Jest] yet but I think maybe this is good change to try the new technology. Since *I think* now I have good understanding of how this package work, I'm confident in replacing mocha with [Jest]. Also it'll be a good experiment before using [Jest] in production. How do you think?

[Jest]: https://facebook.github.io/jest/
[not that comfortable]: https://github.com/simnalamburt/gulp-slm/blob/master/.travis.yml#L15

**Comment by noraesae** [comment]
I do not think the brand new ES features are specifically *necessary* for this small project, especially for testing. What kind of ES features would you like to use? If it's not really essential, I may just stick to the current state.

Also, IMHO the reason Mocha does not support Babel has something to do with decision, not era. Mocha decides to remain simple, and I also would like to do the same.

About test frameworks, I have personally never tried Jest, but heard that it is for React testing. Surely Jest says that it's for general testing, but many people found it difficult and sometimes disappointing to use Jest for usual Node.js behaviour testing. If you just want built-in Babel support for testing, [AVA](https://github.com/avajs/ava) will be a better option.

**Comment by noraesae** [comment]
I come up with another simple solution to use new ES features with Mocha. Install `babel-register` and add `--require babel-register` to the Mocha command. I may prefer this solution if new ES features are really needed.

**Comment by simnalamburt** [comment]
OK that sounds good enough

**Comment by noraesae** [comment]
I also just checked https://github.com/simnalamburt/pen/commit/4932f5f4ad6514ac3199993ac5ce15515abca50b. I am afraid that I am not really a big fan of JSX, and would like to avoid using it if possible. Could you please revert JSX part?

Other changes look wonderful. Great works!

**Comment by simnalamburt** [comment]
@noraesae I separated JSX changes from the PR and made #11 without it. But may I ask why you want to avoid using JSX?

See https://github.com/simnalamburt/pen/commit/d7e5ecbcb413daca5948674f08837f7902098c9d for the separated JSX changes.

**Comment by noraesae** [comment]
It's personal preference, but there are still some reasons.

***The following content are rather subjective, so please ignore it if anyone disagree.***

I do not think implementing JSX was a right decision. It has worked, kind of, but I think it has also added tons of problems in JS ecosystem. First, it surely adds its own JSX compiler. Second, it adds compiler plugins for literally every bundler (or other compiler like Babel). Third, it adds parser plugins for literally every linter and tools. Fourth, it adds plugins for literally every editor. Furthermore, it even forced TypeScript to implement TSX, which was really hard because `<...>` syntax had already been used in TS. In short, it adds something in literally every layer of JS ecosystem.

Some people argue it makes rendering code easy to read. But really? I personally do not understand why React does not just use function syntax.

```js
// for example...
div({ className: 'hello' },
  h1_('i am header 1'),
  h2_('i am header 2')
)
```

Looking exactly same as HTML is great, but I doubt it is really worth the effort and time of tons of people.

***Subjective content finishes...***

About Pen's usage, it does not really include complex rendering logic. It does not even have nested component. To render a single element, there is no problem with `React.createElement`. Adding a dependency is actually a management cost, and I would like to avoid adding one when possible.

I would like to make it clear that I am not arguing that everybody should think the same. It is my personal stand for the time being, and also, thus, of Pen.

I am really sorry again that I cannot accept every request of you, despite your great work and effort.

**Comment by noraesae** [comment]
I am thinking of trying implementing the last parts today. Is there any implementation you are working on?

**Comment by simnalamburt** [comment]
No recently I've become busy and looks like I won't able to do this for a while. Go ahead.

**Comment by simnalamburt** [comment]
There's a small issue with Node 4.x support but looks like it's not major problem. This issue was just closed by 397a1a4045cee6deba6aed39f2d7aff8ec43f31b

**Comment by noraesae** [comment]
Thanks. I really appreciate your great works.
