### ISSUE TITLE
Basic housekeepings

### ISSUE THREAD

**Issue by simnalamburt** [noraesae/pen#4]
I'm currently performing basic houskeepings to this project at [simnalamburt/pen](https://github.com/simnalamburt/pen)

#### TODOs
- Adopt yarn
  - [x] Update `README.md`, `.travis.yml`, etc
  - [x] Check in `yarn.lock`
- Optimize CI (current CI requires ~65s)
  - [x] [Cache dependencies](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn) (~~decrease \~20s~~ &rarr; doesn't give you a real performance improvement)
  - [x] Prevent travis from building the frontend codes twice (decrease ~5s)
- Update CI
  - [x] Resolve all warnings
  - [x] Test multiple node versions (4, 6, node)
- [x] Update dependencies
