### ISSUE TITLE
Replace browserify with webpack

### ISSUE THREAD

**Issue by simnalamburt** [noraesae/pen#6]
Currently `@noraesae/pen` has an issue with [Yarn] because of [this part]:

```pug
doctype html
html
  head
    meta(charset='UTF-8')
    title= basename
    style
      include ../../node_modules/github-markdown-css/github-markdown.css
      #       ^^^^
      #       They do not reside at that location if pen was installed with Yarn! :)
      include style.css
  body
    #app.markdown-body
    script
      include build.js
```

To solve this problem, I'm going to bundle the `github-markdown.css` just like thie `build.js`. This can be done by replacing browserify with [webpack].

#### TODOs
- [x] browserify -> [webpack]
- [x] babelify -> babel-loader
- [x] babel-preset-es2015 -> babel-preset-latest
- [x] Remove uglify-js and use webpack's build-in uglifier instead.
- [x] Bundle libraries as many as possible and move those dependencies from `dependencies` into `devDependencies`
- [x] ~~Replace pug with pure HTML5~~ &rarr; impossible
- [x] ~~Replace pug with another template engine with smaller dependencies~~ &rarr; #7 
- [x] ~~Apply ES2017 syntax (module, etc)~~ &rarr; impossible because of test codes
- [x] Update eslint

Currently working in progress at [simnalamburt/pen](https://github.com/simnalamburt/pen)

[Yarn]: https://yarnpkg.com/
[this part]: https://github.com/noraesae/pen/blob/master/src/template/preview.pug#L7
[webpack]: https://github.com/webpack/webpack#readme

**Comment by noraesae** [comment]
As I suggested in #7, using pure HTML5 is possible with inlining CSS and JS in result HTML. Then we do not need to worry about relpath problem and the result will be much simpler(we do not need `build.js` and `build.css`). It must be possible with webpack, mustn't it?

Yes, it is completely okay to change the project structure, when the result becomes better.

**Comment by simnalamburt** [comment]
It is possible to build HTML file with webpack but it's not major usecase of webpack. I've never used `html-webpack-plugin` with webpack so I need some time to survey.

###### Reference
- https://github.com/DustinJackson/html-webpack-inline-source-plugin

**Comment by noraesae** [comment]
I agree that it is not a good practice for production web app. However, Pen is an offline tool and inlining JS and CSS seems nicer for its simplicity.

If it feels like making work overly complicated, please feel free to let me know. It is still completely okay to use `build.css` and `build.js`.

**Comment by simnalamburt** [comment]
OK. I'll split PR even if I do that `html-webpack-plugin` optimization
